"""added img_url to Detections

Revision ID: c30d6831618c
Revises: ae42815c5dbd
Create Date: 2026-09-21 16:27:48.821764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c30d6831618c'
down_revision: Union[str, Sequence[str], None] = 'ae42815c5dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection', sa.Column('img_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection', 'img_url')
    # ### end Alembic commands ###
